@echo off
echo Setting up Git...
git init
echo Adding Remote...
git remote remove origin
git remote add origin https://github.com/KENNEDY-ONGESA/EGA-Tech.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit force"
echo Renaming branch...
git branch -M main
echo Pushing...
git push -u origin main
pause
